# Generated by Django 2.1.2 on 2019-05-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_productpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
