# Generated by Django 2.1.2 on 2019-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='update',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
