# Generated by Django 2.1.2 on 2019-04-17 11:46

import app_dir.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_dir.products.models.upload_image_path),
        ),
    ]
